package org.hexnodes.hexnodes.game;

public enum AspectEnum {
    EMPTY, TILE,
    AER, AQUA, IGNIS, ORDO, PERDITIO, TERRA,
    GELUM, LUX, MOTUS, PERMUTATIO, POTENTIA,
    TEMPESTAS, VACUOS, VENENUM, VICTUS, VITREUS,
    BESTIA, FAMES, HERBA, ITER, LIMUS, METALLUM,
    MORTUUS, PRAECANTATIO, SANO, TENEBRAE, VINCULUM, VOLATUS,
    ALIENIS, ARBOR, AURAM, CORPUS, EXANIMIS, SPIRITUS, VITIUM,
    COGNITIO, SENSUS, HUMANUS, INSTRUMENTUM, LUCRUM, MESSIS,
    PERFODIO, FABRICO, MACHINA, METO, PANNUS, TELUM, TUTAMEN
}
